### ISSUE TITLE
Apprise Tgram:// notification issue

### ISSUE THREAD

**Issue by zaggash** [dockupdater/dockupdater#28]
**Question**:

Not sure if it is a bug or a failure from my configuration.
I have a notification setup but it fails with: 

```
ERROR : Apprise : Unparseable schema:// found in URL ********tgram://********9525".
ERROR : Apprise : Failed to load notification url: ********tgram://********9525"
ERROR : notifiers : Could not add notifier ********tgram://********9525"
```

Here is how I did it (obvious URL obfuscation) :
```
environment:
      - CRON=0 4 */1 * *
      #- RUN_ONCE=true
      - LOG_LEVEL=info
      #- LOG_LEVEL=debug
      - DOCKER_SOCKETS=unix://var/run/docker.sock
      - CLEANUP=true
      - SKIP_START_NOTIF=true
      - TZ=Europe/Paris
      - NOTIFIERS="tgram://123456789:ABCdefghijkl123456789opqyz/-123456789525"
```

Not sure if it is failing because of tgram://
> Unparseable schema:// found in URL *

or because of the '-' minus sign on the ChatID ( which is a GroupID btw )

I want to add that this notification token is working fine, I use it with another tool and I tested manually.

**Comment by zaggash** [comment]
I did the testing with the virtualenv.

I can send a message successfully with my tgram URL but the same is failling with dockupdater app

**Comment by caronc** [comment]
Hi guys,

I've had a few tickets raised to me that were similar to what you're experiencing.  It turned out that Apprise wasn't properly loaded in the container (making the URLs that would otherwise always work just not work).

You could see if this same thing is impacting you.  From the above i saw that pulling in the Apprise binary you guys were able to make everything work (proving that there is nothing wrong with your URL) so the problem is somewhere in-between it and the program you're using.

The ticket that seems to relate to this is [here](https://github.com/caronc/nzb-notify/issues/69#issuecomment-690552764); the fix:
```bash
# from within the broken container:
# get pip
apk add py3-pip
# ... say yes when prompted; let it add it and dependencies

# Remove hosed copy of apprise that exists in this container
pip uninstall apprise

# Then just re-add it
pip install apprise
```

**Comment by zaggash** [comment]
Hey @caronc 
Thanks to your last comment I finally understood what the problem is.

I used your docker image `dockupdate/dockupdate:latest` which is a 1y old build with a prehistoric version of apprise installed.
I think it would be best to use the `dockupdate/dockupdate:master`

To fix it I created my own image which I re build on regular basis and it is now working like a charm.
